require_relative "ordering/lib/ordering"
require_relative "pricing/lib/pricing"
require_relative "product_catalog/lib/product_catalog"
require_relative "payments/lib/payments"
require_relative "inventory/lib/inventory"
